language: node_js
env: PHANTOMJS_BIN=./node_modules/.bin/phantomjs
node_js:
  - "5"
script:
  - npm run test
after_success:
  - cat ./test/unit/coverage/lcov.info | ./node_modules/.bin/coveralls
